/*
 * @Author: your name
 * @Date: 2020-06-05 11:19:29
 * @LastEditTime: 2020-06-12 14:15:11
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \multi-entry-react-app\src\home\mock.js
 */
import Mock from "mockjs";
export default Mock.mock("/api", {
    status: 200,
    data: {
        slider: [
            {
                "title|10-20": "标题",
                path: "@url",
                tag: "hot",
                imgUrl: "Random.image('200x100')",
                "id|1-100": 100,
            },
            {
                "title|10-20": "标题",
                path: "@url",
                tag: "hot",
                imgUrl: "Random.image('200x100')",
                "id|1-100": 100,
            },
            {
                "title|10-20": "标题",
                path: "@url",
                tag: "hot",
                imgUrl: "Random.image('200x100')",
                "id|1-100": 100,
            },
            {
                "title|10-20": "标题",
                path: "@url",
                tag: "hot",
                imgUrl: "Random.image('200x100')",
                "id|1-100": 100,
            },
        ],
        xnkjg: {
            list: [
                {
                    "title|10-20": "标题",
                    link: "@url",
                    imgUrl: "@url",
                    country: "中国",
                    museum: "中国国家科技馆",
                    joinNum: 12306,
                    isVr: true,
                    "id|1-100": 100,
                },
                {
                    "title|10-20": "标题",
                    link: "@url",
                    imgUrl: "@url",
                    country: "中国",
                    museum: "中国国家科技馆",
                    joinNum: 12306,
                    isVr: true,
                    "id|1-100": 100,
                },
                {
                    "title|10-20": "标题",
                    link: "@url",
                    imgUrl: "@url",
                    country: "中国",
                    museum: "中国国家科技馆",
                    joinNum: 12306,
                    isVr: true,
                    "id|1-100": 100,
                },
                {
                    "title|10-20": "标题",
                    link: "@url",
                    imgUrl: "@url",
                    country: "中国",
                    museum: "中国国家科技馆",
                    joinNum: 12306,
                    isVr: true,
                    "id|1-100": 100,
                },
                {
                    "title|10-20": "标题",
                    link: "@url",
                    imgUrl: "@url",
                    country: "中国",
                    museum: "中国国家科技馆",
                    joinNum: 12306,
                    isVr: true,
                    "id|1-100": 100,
                },
            ],
            id: 123,
            title: "虚拟科技馆",
            moreLink: "@url",
        },
        zykc: {
            list: [
                {
                    "title|10-20": "标题",
                    path: "@url",
                    tag: "new",
                    imgUrl: "@url",
                    joinNum: 12306,
                    star: 1,
                    comment: 12415,
                    "id|1-100": 100,
                    isHot: 1,
                    isRecommended: 0,
                    isLatest: 0,
                },
                {
                    "title|5-20": "标题",
                    path: "@url",
                    tag: "new",
                    imgUrl: "@url",
                    joinNum: 12306,
                    star: 2,
                    comment: 12415,
                    "id|1-100": 100,
                    isHot: 0,
                    isRecommended: 1,
                    isLatest: 0,
                },
                {
                    "title|10-20": "标题",
                    path: "@url",
                    tag: "new",
                    imgUrl: "@url",
                    joinNum: 12306,
                    star: 3,
                    comment: 12415,
                    "id|1-100": 100,
                    isHot: 0,
                    isRecommended: 0,
                    isLatest: 1,
                },
                {
                    "title|10-20": "标题",
                    path: "@url",
                    tag: "new",
                    imgUrl: "@url",
                    joinNum: 12306,
                    star: 4,
                    comment: 12415,
                    "id|1-100": 100,
                    isHot: 1,
                    isRecommended: 0,
                    isLatest: 0,
                },
            ],
            id: 123,
            title: "专业课程",
            moreLink: "@url",
        },
        kxhdal: {
            list: [
                {
                    "title|10-20": "标题",
                    imgUrl: "@url",
                    no: "G7-G9",
                    museum: "中国国家科技馆",
                    country: "中国",
                    "abstract|20-40": "标题",
                    link: "@url",
                    "id|1-100": 100,
                },
                {
                    "title|10-20": "标题",
                    imgUrl: "@url",
                    no: "G7-G97",
                    museum: "中国国家科技馆",
                    country: "中国",
                    "abstract|20-40": "标题",
                    link: "@url",
                    "id|1-100": 100,
                },
            ],
            "id: |1-100": 100,
            title: "科学活动案例",
            moreLink: "@url",
        },
        kjzy: {
            list: [
                {
                    "title|10-20": "标题",
                    imgUrl: "@url",
                    "abstract|20-40": "标题",
                    link: "@url",
                    time: "@time",
                    source: "中国科技馆",
                    "id|1-100": 100,
                },
                {
                    "title|10-20": "标题",
                    imgUrl: "@url",
                    "abstract|20-40": "标题",
                    link: "@url",
                    time: "@time",
                    source: "中国科技馆",
                    "id|1-100": 100,
                },
                {
                    "title|10-20": "标题",
                    imgUrl: "@url",
                    "abstract|20-40": "标题",
                    link: "@url",
                    time: "@time",
                    source: "中国科技馆",
                    "id|1-100": 100,
                },
                {
                    "title|10-20": "标题",
                    imgUrl: "@url",
                    "abstract|20-40": "标题",
                    link: "@url",
                    time: "@time",
                    source: "中国科技馆",
                    "id|1-100": 100,
                },
            ],
            "id: |1-100": 100,
            title: "科教资源",
            moreLink: "@url",
        },
        zthd: {
            list: [
                {
                    imgUrl: "@url",
                    link: "@url",
                    "id|1-100": 100,
                },
                {
                    imgUrl: "@url",
                    link: "@url",
                    "id|1-100": 100,
                },
                {
                    imgUrl: "@url",
                    link: "@url",
                    "id|1-100": 100,
                },
            ],
            "id: |1-100": 100,
            title: "主题活动",
            moreLink: "@url",
        },
    },
    //data里的属性看不懂，需要详细看语法规范,博客链接:https://www.jianshu.com/p/4579f40e6108
});
